### ISSUE TITLE
Missing sofia_fields.sql

### ISSUE THREAD

**Issue by manuparra** [AusSRC/SoFiAX_services#11]
Hi @axshen could you check this entry in `init.sh` :
https://github.com/AusSRC/SoFiAX_services/blob/f8e784d24b093213f864808684dc59500b8e7f8a/db/init.sh#L9

I miss `sofia_fields.sql` within `db` folder. Is it right?

**Comment by axshen** [comment]
Hi @manuparra thanks for bringing this up - I have removed that file as the database update script has been moved to the `db.sql` file.

**Comment by manuparra** [comment]
Thanks! Just to avoid inconsistencies.
